export const PUNJAB_DISTRICTS: { name: string; tehsils: string[] }[] = [
  { name: "Amritsar", tehsils: ["Amritsar", "Ajnala", "Baba Bakala", "Majitha", "Atari", "Rajasansi"] },
  { name: "Barnala", tehsils: ["Barnala", "Tapa", "Mehal Kalan", "Sehna"] },
  { name: "Bathinda", tehsils: ["Bathinda", "Rampura Phul", "Phul", "Talwandi Sabo", "Maur", "Nathana"] },
  { name: "Faridkot", tehsils: ["Faridkot", "Jaito", "Kotkapura"] },
  { name: "Fatehgarh Sahib", tehsils: ["Fatehgarh Sahib", "Amloh", "Khamanon", "Bassi Pathana"] },
  { name: "Fazilka", tehsils: ["Fazilka", "Abohar", "Jalalabad"] },
  { name: "Ferozepur", tehsils: ["Ferozepur", "Guru Har Sahai", "Zira", "Makhu"] },
  { name: "Gurdaspur", tehsils: ["Gurdaspur", "Batala", "Dinanagar", "Dera Baba Nanak", "Dhariwal", "Qadian"] },
  { name: "Hoshiarpur", tehsils: ["Hoshiarpur", "Mukerian", "Dasuya", "Tanda", "Garhshankar"] },
  { name: "Jalandhar", tehsils: ["Jalandhar", "Nakodar", "Phillaur", "Shahkot", "Adampur"] },
  { name: "Kapurthala", tehsils: ["Kapurthala", "Phagwara", "Sultanpur Lodhi", "Bhulath"] },
  { name: "Ludhiana", tehsils: ["Ludhiana", "Samrala", "Khanna", "Jagraon", "Raikot", "Payal"] },
  { name: "Malerkotla", tehsils: ["Malerkotla", "Amargarh", "Ahmedgarh"] },
  { name: "Mansa", tehsils: ["Mansa", "Budhlada", "Sardulgarh", "Bareta"] },
  { name: "Moga", tehsils: ["Moga", "Nihal Singh Wala", "Baghapurana", "Dharamkot"] },
  { name: "Pathankot", tehsils: ["Pathankot", "Sujanpur", "Dhar Kalan"] },
  { name: "Patiala", tehsils: ["Patiala", "Rajpura", "Samana", "Nabha", "Patran"] },
  { name: "Rupnagar", tehsils: ["Rupnagar", "Anandpur Sahib", "Morinda", "Chamkaur Sahib", "Kiratpur Sahib"] },
  { name: "SAS Nagar (Mohali)", tehsils: ["Mohali", "Kharar", "Dera Bassi"] },
  { name: "Sangrur", tehsils: ["Sangrur", "Sunam", "Lehragaga", "Dhuri"] },
  { name: "SBS Nagar (Nawanshahr)", tehsils: ["Nawanshahr", "Balachaur", "Banga"] },
  { name: "Sri Muktsar Sahib", tehsils: ["Muktsar", "Malout", "Gidderbaha", "Lambi"] },
  { name: "Tarn Taran", tehsils: ["Tarn Taran", "Patti", "Khem Karan", "Bhikhiwind"] },
];
